#指定语言环境
language: node_js
#指定需要sudo权限
sudo: required
#指定版本
node_js:
  - 9.8.0 
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
 directories:
   - node_modules

#指定源码分支
branches:
  only:
    - hexo

before_install:
  - npm install -g hexo-cli
# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

     # 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "sjt157"
  - git config user.email "1872963677@qq.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" _config.yml
  - hexo -d


